Add rgb-primary-text-color to fix missing Hover effect
home-assistant-community-themes/blue-night pull request #19
Opened 2020-09-28 12:29 UTC by sdrapha

Add rgb-primary-text-color to fix missing Hover effect

The rgb value is needed for the hover effect, this variable is used inside a rgba function, if the value is missing the hover effect fails.

2020-09-29 15:45 UTC, maartenpaauw commented on themes/blue_night.yaml
> +  rgb-primary-text-color: "0, 120 , 160"
Could you please keep this list alphabetically ordered?

2020-09-29 15:46 UTC, maartenpaauw requested changes
Thanks for your submission!

Could you please keep the list alphabetically ordered?

2020-09-29 20:10 UTC, sdrapha commented
> 
> 
> Thanks for your submission!
> 
> Could you please keep the list alphabetically ordered?

Sure. Done. Thank you for reviewing it.

2020-09-30 17:37 UTC, maartenpaauw approved these changes

2020-09-30 17:38 UTC, merged